#!/bin/sh

# Copyright 2015 Canonical
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

if ! pgrep -f unity-system-compositor ; then
    # start X server if we're not running Mir
    export DISPLAY=:5
    Xvfb ${DISPLAY} -screen 0 1024x768x24 >/tmp/Xvfb-5.log 2>&1 &
    export XAUTHORITY=/dev/null
fi

autopilot3 run -v -f subunit -o $ADT_ARTIFACTS webapp_container
