/*
 * Copyright 2014 Canonical Ltd.
 *
 * This file is part of webbrowser-app.
 *
 * webbrowser-app is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * webbrowser-app is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Hide and remove so-called "smart banners" generated by the smartbanner jQuery
// plugin (http://jasny.github.io/jquery.smartbanner/) that advertise native
// Android/iOS applications based on a very naïve parsing of the UA string.

var smartbanner = document.getElementById("smartbanner");
if (smartbanner !== null) {
    if (smartbanner.classList.contains("shown")) {
        // FIXME: unfortunately this doesn’t prevent the original slide-in
        // animation from starting, which results in the contents of the page
        // briefly sliding down then up again, which doesn’t look too nice.
        // Ideally, we should prevent the banner from even being instantiated
        // and inserted in the DOM in the first place.
        smartbanner.style.display = "none";
        var a = smartbanner.getElementsByClassName("sb-close");
        if (a.length === 1) {
            a[0].click();
        }
    }
    smartbanner.parentNode.removeChild(smartbanner);
}
