/*
 * Copyright 2014-2015 Canonical Ltd.
 *
 * This file is part of webbrowser-app.
 *
 * webbrowser-app is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * webbrowser-app is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
'use strict';

function getExtension(filename) {
    var filenameParts = filename.split(".");
    if (filenameParts.length === 1 || (filenameParts[0] === "" && filenameParts.length === 2)) {
        return ""
    }
    return filenameParts.pop().toLowerCase();
}

// Constructed from /etc/mime.types
function filenameToContentType(filename) {
    switch(getExtension(filename)) {
        case "art":
        case "bmp":
        case "cdr":
        case "cdt":
        case "cpt":
        case "cr2":
        case "crw":
        case "djv":
        case "djvu":
        case "erf":
        case "gif":
        case "ico":
        case "ief":
        case "jng":
        case "jp2":
        case "jpe":
        case "jpeg":
        case "jpf":
        case "jpg":
        case "jpg2":
        case "jpm":
        case "jpx":
        case "nef":
        case "orf":
        case "pat":
        case "pbm":
        case "pcx":
        case "pgm":
        case "png":
        case "pnm":
        case "ppm":
        case "psd":
        case "ras":
        case "rgb":
        case "svg":
        case "svgz":
        case "tif":
        case "tiff":
        case "wbmp":
        case "xbm":
        case "xpm":
        case "xwd":
            return ContentType.Pictures;
        case "3gp":
        case "asf":
        case "asx":
        case "avi":
        case "axv":
        case "dif":
        case "dl":
        case "dv":
        case "fli":
        case "flv":
        case "gl":
        case "lsf":
        case "lsx":
        case "m4v":
        case "mkv":
        case "mng":
        case "mov":
        case "movie":
        case "mp4":
        case "mpe":
        case "mpeg":
        case "mpg":
        case "mpv":
        case "mxu":
        case "ogv":
        case "qt":
        case "ts":
        case "webm":
        case "wm":
        case "wmv":
        case "wmx":
        case "wvx":
            return ContentType.Videos;
        case "aif":
        case "aifc":
        case "aiff":
        case "amr":
        case "au":
        case "awb":
        case "axa":
        case "csd":
        case "flac":
        case "gsm":
        case "kar":
        case "m3u":
        case "m4a":
        case "mid":
        case "midi":
        case "mp2":
        case "mp3":
        case "mpega":
        case "mpga":
        case "oga":
        case "ogg":
        case "opus":
        case "orc":
        case "pls":
        case "ra":
        case "ram":
        case "rm":
        case "sco":
        case "sd2":
        case "sid":
        case "snd":
        case "spx":
        case "wav":
        case "wax":
        case "wma":
            return ContentType.Music;
        case "vcard":
        case "vcf":
            return ContentType.Contacts;
        case "323":
        case "appcache":
        case "asc":
        case "bib":
        case "boo":
        case "brf":
        case "c":
        case "c++":
        case "cc":
        case "cls":
        case "cpp":
        case "csh":
        case "css":
        case "csv":
        case "cxx":
        case "d":
        case "diff":
        case "etx":
        case "gcd":
        case "h":
        case "hh":
        case "h++":
        case "hpp":
        case "hs":
        case "htc":
        case "htm":
        case "html":
        case "hxx":
        case "ics":
        case "icz":
        case "jad":
        case "java":
        case "lhs":
        case "ltx":
        case "ly":
        case "mml":
        case "moc":
        case "p":
        case "pas":
        case "patch":
        case "pdf":
        case "pl":
        case "pm":
        case "pot":
        case "py":
        case "rtx":
        case "scala":
        case "sct":
        case "sfv":
        case "sh":
        case "shtml":
        case "srt":
        case "sty":
        case "tcl":
        case "tex":
        case "text":
        case "tk":
        case "tm":
        case "tsv":
        case "ttl":
        case "txt":
        case "uls":
        case "vcs":
        case "wml":
        case "wmls":
        case "wsc":
            return ContentType.Documents;
        case "epub":
        case "mobi":
        case "lit":
        case "fb2":
        case "azw":
        case "tpz":
            return ContentType.EBooks;
        default:
            return ContentType.Unknown;
    }
}

// Constructed from /etc/mime.types
function filenameToMimeType(filename) {
    switch(getExtension(filename)) {
        case "%":
        case "bak":
        case "old":
        case "sik":
        case "~":
            return "application/x-trash";
        case "323":
            return "text/h323";
        case "3gp":
            return "video/3gpp";
        case "7z":
            return "application/x-7z-compressed";
        case "abw":
            return "application/x-abiword";
        case "ai":
        case "eps":
        case "eps2":
        case "eps3":
        case "epsf":
        case "epsi":
        case "ps":
            return "application/postscript";
        case "aif":
        case "aifc":
        case "aiff":
            return "audio/x-aiff";
        case "alc":
            return "chemical/x-alchemy";
        case "amr":
            return "audio/amr";
        case "anx":
            return "application/annodex";
        case "apk":
            return "application/vnd.android.package-archive";
        case "appcache":
            return "text/cache-manifest";
        case "art":
            return "image/x-jg";
        case "asc":
        case "brf":
        case "pot":
        case "srt":
        case "text":
        case "txt":
            return "text/plain";
        case "asf":
        case "asx":
            return "video/x-ms-asf";
        case "asn":
            return "chemical/x-ncbi-asn1";
        case "asn":
            return "chemical/x-ncbi-asn1-spec";
        case "asn":
            return "chemical/x-ncbi-asn1";
        case "asn":
            return "chemical/x-ncbi-asn1-spec";
        case "aso":
        case "val":
            return "chemical/x-ncbi-asn1-binary";
        case "atom":
            return "application/atom+xml";
        case "atomcat":
            return "application/atomcat+xml";
        case "atomsrv":
            return "application/atomserv+xml";
        case "au":
        case "snd":
            return "audio/basic";
        case "avi":
            return "video/x-msvideo";
        case "awb":
            return "audio/amr-wb";
        case "axa":
            return "audio/annodex";
        case "axv":
            return "video/annodex";
        case "b":
            return "chemical/x-molconn-Z";
        case "bat":
        case "com":
        case "dll":
        case "exe":
            return "application/x-msdos-program";
        case "bcpio":
            return "application/x-bcpio";
        case "bib":
            return "text/x-bibtex";
        case "bin":
            return "application/octet-stream";
        case "bmp":
            return "image/x-ms-bmp";
        case "boo":
            return "text/x-boo";
        case "book":
        case "fb":
        case "fbdoc":
        case "fm":
        case "frame":
        case "frm":
        case "maker":
            return "application/x-maker";
        case "bsd":
            return "chemical/x-crossfire";
        case "c":
            return "text/x-csrc";
        case "c++":
        case "cc":
        case "cpp":
        case "cxx":
            return "text/x-c++src";
        case "c3d":
            return "chemical/x-chem3d";
        case "cab":
            return "application/x-cab";
        case "cac":
        case "cache":
            return "chemical/x-cache";
        case "cap":
        case "pcap":
            return "application/vnd.tcpdump.pcap";
        case "cascii":
        case "cbin":
        case "ctab":
            return "chemical/x-cactvs-binary";
        case "cat":
            return "application/vnd.ms-pki.seccat";
        case "cbr":
            return "application/x-cbr";
        case "cbz":
            return "application/x-cbz";
        case "cda":
        case "cdf":
            return "application/x-cdf";
        case "cdr":
            return "image/x-coreldraw";
        case "cdt":
            return "image/x-coreldrawtemplate";
        case "cdx":
            return "chemical/x-cdx";
        case "cdy":
            return "application/vnd.cinderella";
        case "cef":
        case "cxf":
            return "chemical/x-cxf";
        case "cer":
            return "chemical/x-cerius";
        case "chm":
            return "chemical/x-chemdraw";
        case "chrt":
            return "application/x-kchart";
        case "cif":
            return "chemical/x-cif";
        case "class":
            return "application/java-vm";
        case "cls":
        case "ltx":
        case "sty":
        case "tex":
            return "text/x-tex";
        case "cmdf":
            return "chemical/x-cmdf";
        case "cml":
            return "chemical/x-cml";
        case "cod":
            return "application/vnd.rim.cod";
        case "cpa":
            return "chemical/x-compass";
        case "cpio":
            return "application/x-cpio";
        case "cpt":
            return "image/x-corelphotopaint";
        case "cpt":
            return "application/mac-compactpro";
        case "cpt":
            return "image/x-corelphotopaint";
        case "cpt":
            return "application/mac-compactpro";
        case "cr2":
            return "image/x-canon-cr2";
        case "crl":
            return "application/x-pkcs7-crl";
        case "crt":
            return "application/x-x509-ca-cert";
        case "crw":
            return "image/x-canon-crw";
        case "csd":
        case "orc":
        case "sco":
            return "audio/csound";
        case "csf":
            return "chemical/x-cache-csf";
        case "csh":
            return "application/x-csh";
        case "csh":
            return "text/x-csh";
        case "csh":
            return "application/x-csh";
        case "csh":
            return "text/x-csh";
        case "csm":
        case "csml":
            return "chemical/x-csml";
        case "css":
            return "text/css";
        case "csv":
            return "text/csv";
        case "ctx":
            return "chemical/x-ctx";
        case "cu":
            return "application/cu-seeme";
        case "cub":
            return "chemical/x-gaussian-cube";
        case "d":
            return "text/x-dsrc";
        case "davmount":
            return "application/davmount+xml";
        case "dcm":
            return "application/dicom";
        case "dcr":
        case "dir":
        case "dxr":
            return "application/x-director";
        case "ddeb":
        case "deb":
        case "udeb":
            return "application/vnd.debian.binary-package";
        case "deb":
        case "udeb":
            return "application/x-debian-package";
        case "dif":
        case "dv":
            return "video/dv";
        case "diff":
        case "patch":
            return "text/x-diff";
        case "djv":
        case "djvu":
            return "image/vnd.djvu";
        case "dl":
            return "video/dl";
        case "dmg":
            return "application/x-apple-diskimage";
        case "dms":
            return "application/x-dms";
        case "doc":
        case "dot":
            return "application/msword";
        case "docm":
            return "application/vnd.ms-word.document.macroEnabled.12";
        case "docx":
            return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        case "dotm":
            return "application/vnd.ms-word.template.macroEnabled.12";
        case "dotx":
            return "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
        case "dvi":
            return "application/x-dvi";
        case "dx":
        case "jdx":
            return "chemical/x-jcamp-dx";
        case "emb":
        case "embl":
            return "chemical/x-embl-dl-nucleotide";
        case "eml":
            return "message/rfc822";
        case "ent":
        case "prt":
            return "chemical/x-ncbi-asn1-ascii";
        case "ent":
        case "pdb":
            return "chemical/x-pdb";
        case "ent":
        case "prt":
            return "chemical/x-ncbi-asn1-ascii";
        case "ent":
        case "pdb":
            return "chemical/x-pdb";
        case "eot":
            return "application/vnd.ms-fontobject";
        case "erf":
            return "image/x-epson-erf";
        case "es":
            return "application/ecmascript";
        case "etx":
            return "text/x-setext";
        case "ez":
            return "application/andrew-inset";
        case "fch":
        case "fchk":
            return "chemical/x-gaussian-checkpoint";
        case "fig":
            return "application/x-xfig";
        case "flac":
            return "audio/flac";
        case "fli":
            return "video/fli";
        case "flv":
            return "video/x-flv";
        case "gal":
            return "chemical/x-gaussian-log";
        case "gam":
        case "gamin":
        case "inp":
            return "chemical/x-gamess-input";
        case "gan":
            return "application/x-ganttproject";
        case "gau":
        case "gjc":
        case "gjf":
            return "chemical/x-gaussian-input";
        case "gcd":
            return "text/x-pcs-gcd";
        case "gcf":
            return "application/x-graphing-calculator";
        case "gcg":
            return "chemical/x-gcg8-sequence";
        case "gen":
            return "chemical/x-genbank";
        case "gf":
            return "application/x-tex-gf";
        case "gif":
            return "image/gif";
        case "gl":
            return "video/gl";
        case "gnumeric":
            return "application/x-gnumeric";
        case "gpt":
            return "chemical/x-mopac-graph";
        case "gsf":
        case "pfa":
        case "pfb":
            return "application/x-font";
        case "gsm":
            return "audio/x-gsm";
        case "gtar":
            return "application/x-gtar";
        case "gz":
            return "application/gzip";
        case "h":
            return "text/x-chdr";
        case "h++":
        case "hh":
        case "hpp":
        case "hxx":
            return "text/x-c++hdr";
        case "hdf":
            return "application/x-hdf";
        case "hin":
            return "chemical/x-hin";
        case "hqx":
            return "application/mac-binhex40";
        case "hs":
            return "text/x-haskell";
        case "hta":
            return "application/hta";
        case "htc":
            return "text/x-component";
        case "htm":
        case "html":
        case "shtml":
            return "text/html";
        case "hwp":
            return "application/x-hwp";
        case "ica":
            return "application/x-ica";
        case "ice":
            return "x-conference/x-cooltalk";
        case "ico":
            return "image/vnd.microsoft.icon";
        case "ics":
        case "icz":
            return "text/calendar";
        case "ief":
            return "image/ief";
        case "iges":
        case "igs":
            return "model/iges";
        case "iii":
            return "application/x-iphone";
        case "info":
            return "application/x-info";
        case "ins":
        case "isp":
            return "application/x-internet-signup";
        case "iso":
            return "application/x-iso9660-image";
        case "ist":
        case "istr":
            return "chemical/x-isostar";
        case "jad":
            return "text/vnd.sun.j2me.app-descriptor";
        case "jam":
            return "application/x-jam";
        case "jar":
            return "application/java-archive";
        case "java":
            return "text/x-java";
        case "jmz":
            return "application/x-jmol";
        case "jng":
            return "image/x-jng";
        case "jnlp":
            return "application/x-java-jnlp-file";
        case "jp2":
        case "jpg2":
            return "image/jp2";
        case "jpe":
        case "jpeg":
        case "jpg":
            return "image/jpeg";
        case "jpf":
        case "jpx":
            return "image/jpx";
        case "jpm":
            return "image/jpm";
        case "js":
            return "application/javascript";
        case "json":
            return "application/json";
        case "kar":
        case "mid":
        case "midi":
            return "audio/midi";
        case "key":
            return "application/pgp-keys";
        case "kil":
            return "application/x-killustrator";
        case "kin":
            return "chemical/x-kinemage";
        case "kml":
            return "application/vnd.google-earth.kml+xml";
        case "kmz":
            return "application/vnd.google-earth.kmz";
        case "kpr":
        case "kpt":
            return "application/x-kpresenter";
        case "ksp":
            return "application/x-kspread";
        case "kwd":
        case "kwt":
            return "application/x-kword";
        case "latex":
            return "application/x-latex";
        case "lha":
            return "application/x-lha";
        case "lhs":
            return "text/x-literate-haskell";
        case "lin":
            return "application/bbolin";
        case "lsf":
        case "lsx":
            return "video/x-la-asf";
        case "ly":
            return "text/x-lilypond";
        case "lyx":
            return "application/x-lyx";
        case "lzh":
            return "application/x-lzh";
        case "lzx":
            return "application/x-lzx";
        case "m3g":
            return "application/m3g";
        case "m3u":
            return "audio/x-mpegurl";
        case "m3u":
            return "audio/mpegurl";
        case "m3u":
            return "audio/x-mpegurl";
        case "m3u":
            return "audio/mpegurl";
        case "m3u8":
            return "application/x-mpegURL";
        case "m4a":
        case "mp2":
        case "mp3":
        case "mpega":
        case "mpga":
            return "audio/mpeg";
        case "man":
            return "application/x-troff-man";
        case "mbox":
            return "application/mbox";
        case "mcif":
            return "chemical/x-mmcif";
        case "mcm":
            return "chemical/x-macmolecule";
        case "mdb":
            return "application/msaccess";
        case "me":
            return "application/x-troff-me";
        case "mesh":
        case "msh":
        case "silo":
            return "model/mesh";
        case "mif":
            return "application/x-mif";
        case "mkv":
        case "mpv":
            return "video/x-matroska";
        case "mm":
            return "application/x-freemind";
        case "mmd":
        case "mmod":
            return "chemical/x-macromodel-input";
        case "mmf":
            return "application/vnd.smaf";
        case "mml":
            return "text/mathml";
        case "mng":
            return "video/x-mng";
        case "moc":
            return "text/x-moc";
        case "mol":
            return "chemical/x-mdl-molfile";
        case "mol2":
            return "chemical/x-mol2";
        case "moo":
            return "chemical/x-mopac-out";
        case "mop":
        case "mopcrt":
        case "mpc":
        case "zmt":
            return "chemical/x-mopac-input";
        case "mov":
        case "qt":
            return "video/quicktime";
        case "movie":
            return "video/x-sgi-movie";
        case "mp4":
            return "video/mp4";
        case "mpe":
        case "mpeg":
        case "mpg":
            return "video/mpeg";
        case "mph":
            return "application/x-comsol";
        case "ms":
            return "application/x-troff-ms";
        case "msi":
            return "application/x-msi";
        case "mvb":
            return "chemical/x-mopac-vib";
        case "mxf":
            return "application/mxf";
        case "mxu":
            return "video/vnd.mpegurl";
        case "nb":
        case "nbp":
            return "application/mathematica";
        case "nc":
            return "application/x-netcdf";
        case "nef":
            return "image/x-nikon-nef";
        case "nwc":
            return "application/x-nwc";
        case "o":
            return "application/x-object";
        case "oda":
            return "application/oda";
        case "odb":
            return "application/vnd.oasis.opendocument.database";
        case "odc":
            return "application/vnd.oasis.opendocument.chart";
        case "odf":
            return "application/vnd.oasis.opendocument.formula";
        case "odg":
            return "application/vnd.oasis.opendocument.graphics";
        case "odi":
            return "application/vnd.oasis.opendocument.image";
        case "odm":
            return "application/vnd.oasis.opendocument.text-master";
        case "odp":
            return "application/vnd.oasis.opendocument.presentation";
        case "ods":
            return "application/vnd.oasis.opendocument.spreadsheet";
        case "odt":
            return "application/vnd.oasis.opendocument.text";
        case "oga":
        case "ogg":
        case "opus":
        case "spx":
            return "audio/ogg";
        case "ogv":
            return "video/ogg";
        case "ogx":
            return "application/ogg";
        case "one":
        case "onepkg":
        case "onetmp":
        case "onetoc2":
            return "application/onenote";
        case "opf":
            return "application/oebps-package+xml";
        case "orf":
            return "image/x-olympus-orf";
        case "otf":
        case "ttf":
            return "application/font-sfnt";
        case "otg":
            return "application/vnd.oasis.opendocument.graphics-template";
        case "oth":
            return "application/vnd.oasis.opendocument.text-web";
        case "otp":
            return "application/vnd.oasis.opendocument.presentation-template";
        case "ots":
            return "application/vnd.oasis.opendocument.spreadsheet-template";
        case "ott":
            return "application/vnd.oasis.opendocument.text-template";
        case "oza":
            return "application/x-oz-application";
        case "p":
        case "pas":
            return "text/x-pascal";
        case "p7r":
            return "application/x-pkcs7-certreqresp";
        case "pac":
            return "application/x-ns-proxy-autoconfig";
        case "pat":
            return "image/x-coreldrawpattern";
        case "pbm":
            return "image/x-portable-bitmap";
        case "pcf":
        case "pcf.Z":
            return "application/x-font-pcf";
        case "pcx":
            return "image/pcx";
        case "pdf":
            return "application/pdf";
        case "pfr":
            return "application/font-tdpfr";
        case "pgm":
            return "image/x-portable-graymap";
        case "pgn":
            return "application/x-chess-pgn";
        case "pgp":
            return "application/pgp-encrypted";
        case "pk":
            return "application/x-tex-pk";
        case "pl":
        case "pm":
            return "text/x-perl";
        case "pls":
            return "audio/x-scpls";
        case "png":
            return "image/png";
        case "pnm":
            return "image/x-portable-anymap";
        case "potm":
            return "application/vnd.ms-powerpoint.template.macroEnabled.12";
        case "potx":
            return "application/vnd.openxmlformats-officedocument.presentationml.template";
        case "ppam":
            return "application/vnd.ms-powerpoint.addin.macroEnabled.12";
        case "ppm":
            return "image/x-portable-pixmap";
        case "pps":
        case "ppt":
            return "application/vnd.ms-powerpoint";
        case "ppsm":
            return "application/vnd.ms-powerpoint.slideshow.macroEnabled.12";
        case "ppsx":
            return "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
        case "pptm":
            return "application/vnd.ms-powerpoint.presentation.macroEnabled.12";
        case "pptx":
            return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        case "prf":
            return "application/pics-rules";
        case "psd":
            return "image/x-photoshop";
        case "py":
            return "text/x-python";
        case "pyc":
        case "pyo":
            return "application/x-python-code";
        case "qgs":
        case "shp":
        case "shx":
            return "application/x-qgis";
        case "qtl":
            return "application/x-quicktimeplayer";
        case "ra":
        case "ram":
        case "rm":
            return "audio/x-pn-realaudio";
        case "ra":
            return "audio/x-realaudio";
        case "ra":
        case "ram":
        case "rm":
            return "audio/x-pn-realaudio";
        case "ra":
            return "audio/x-realaudio";
        case "rar":
            return "application/rar";
        case "ras":
            return "image/x-cmu-raster";
        case "rb":
            return "application/x-ruby";
        case "rd":
            return "chemical/x-mdl-rdfile";
        case "rdf":
            return "application/rdf+xml";
        case "rdp":
            return "application/x-rdp";
        case "rgb":
            return "image/x-rgb";
        case "roff":
        case "t":
        case "tr":
            return "application/x-troff";
        case "ros":
            return "chemical/x-rosdal";
        case "rpm":
            return "application/x-redhat-package-manager";
        case "rss":
            return "application/x-rss+xml";
        case "rtf":
            return "application/rtf";
        case "rtx":
            return "text/richtext";
        case "rxn":
            return "chemical/x-mdl-rxnfile";
        case "scala":
            return "text/x-scala";
        case "sce":
        case "sci":
            return "application/x-scilab";
        case "scr":
            return "application/x-silverlight";
        case "sct":
        case "wsc":
            return "text/scriptlet";
        case "sd":
        case "sdf":
            return "chemical/x-mdl-sdfile";
        case "sd2":
            return "audio/x-sd2";
        case "sda":
            return "application/vnd.stardivision.draw";
        case "sdc":
            return "application/vnd.stardivision.calc";
        case "sdd":
            return "application/vnd.stardivision.impress";
        case "sdf":
            return "application/vnd.stardivision.math";
        case "sds":
            return "application/vnd.stardivision.chart";
        case "sdw":
            return "application/vnd.stardivision.writer";
        case "ser":
            return "application/java-serialized-object";
        case "sfd":
            return "application/vnd.font-fontforge-sfd";
        case "sfv":
            return "text/x-sfv";
        case "sgf":
            return "application/x-go-sgf";
        case "sgl":
            return "application/vnd.stardivision.writer-global";
        case "sh":
            return "application/x-sh";
        case "sh":
            return "text/x-sh";
        case "sh":
            return "application/x-sh";
        case "sh":
            return "text/x-sh";
        case "shar":
            return "application/x-shar";
        case "sid":
            return "audio/prs.sid";
        case "sig":
            return "application/pgp-signature";
        case "sis":
            return "application/vnd.symbian.install";
        case "sisx":
            return "x-epoc/x-sisx-app";
        case "sit":
        case "sitx":
            return "application/x-stuffit";
        case "skd":
        case "skm":
        case "skp":
        case "skt":
            return "application/x-koan";
        case "sldm":
            return "application/vnd.ms-powerpoint.slide.macroEnabled.12";
        case "sldx":
            return "application/vnd.openxmlformats-officedocument.presentationml.slide";
        case "smi":
        case "smil":
            return "application/smil+xml";
        case "spc":
            return "chemical/x-galactic-spc";
        case "spl":
            return "application/futuresplash";
        case "spl":
            return "application/x-futuresplash";
        case "spl":
            return "application/futuresplash";
        case "spl":
            return "application/x-futuresplash";
        case "sql":
            return "application/x-sql";
        case "src":
            return "application/x-wais-source";
        case "stc":
            return "application/vnd.sun.xml.calc.template";
        case "std":
            return "application/vnd.sun.xml.draw.template";
        case "sti":
            return "application/vnd.sun.xml.impress.template";
        case "stl":
            return "application/sla";
        case "stw":
            return "application/vnd.sun.xml.writer.template";
        case "sv4cpio":
            return "application/x-sv4cpio";
        case "sv4crc":
            return "application/x-sv4crc";
        case "svg":
        case "svgz":
            return "image/svg+xml";
        case "sw":
            return "chemical/x-swissprot";
        case "swf":
        case "swfl":
            return "application/x-shockwave-flash";
        case "sxc":
            return "application/vnd.sun.xml.calc";
        case "sxd":
            return "application/vnd.sun.xml.draw";
        case "sxg":
            return "application/vnd.sun.xml.writer.global";
        case "sxi":
            return "application/vnd.sun.xml.impress";
        case "sxm":
            return "application/vnd.sun.xml.math";
        case "sxw":
            return "application/vnd.sun.xml.writer";
        case "tar":
            return "application/x-tar";
        case "taz":
        case "tgz":
            return "application/x-gtar-compressed";
        case "tcl":
            return "application/x-tcl";
        case "tcl":
        case "tk":
            return "text/x-tcl";
        case "tcl":
            return "application/x-tcl";
        case "tcl":
        case "tk":
            return "text/x-tcl";
        case "texi":
        case "texinfo":
            return "application/x-texinfo";
        case "tgf":
            return "chemical/x-mdl-tgf";
        case "thmx":
            return "application/vnd.ms-officetheme";
        case "tif":
        case "tiff":
            return "image/tiff";
        case "tm":
            return "text/texmacs";
        case "torrent":
            return "application/x-bittorrent";
        case "ts":
            return "video/MP2T";
        case "tsp":
            return "application/dsptype";
        case "tsv":
            return "text/tab-separated-values";
        case "ttl":
            return "text/turtle";
        case "uls":
            return "text/iuls";
        case "ustar":
            return "application/x-ustar";
        case "vcard":
        case "vcf":
            return "text/vcard";
        case "vcd":
            return "application/x-cdlink";
        case "vcs":
            return "text/x-vcalendar";
        case "vmd":
            return "chemical/x-vmd";
        case "vms":
            return "chemical/x-vamas-iso14976";
        case "vrm":
        case "vrml":
        case "wrl":
            return "x-world/x-vrml";
        case "vrml":
        case "wrl":
            return "model/vrml";
        case "vsd":
        case "vss":
        case "vst":
        case "vsw":
            return "application/vnd.visio";
        case "wad":
            return "application/x-doom";
        case "wav":
            return "audio/x-wav";
        case "wax":
            return "audio/x-ms-wax";
        case "wbmp":
            return "image/vnd.wap.wbmp";
        case "wbxml":
            return "application/vnd.wap.wbxml";
        case "webm":
            return "video/webm";
        case "wk":
            return "application/x-123";
        case "wm":
            return "video/x-ms-wm";
        case "wma":
            return "audio/x-ms-wma";
        case "wmd":
            return "application/x-ms-wmd";
        case "wml":
            return "text/vnd.wap.wml";
        case "wmlc":
            return "application/vnd.wap.wmlc";
        case "wmls":
            return "text/vnd.wap.wmlscript";
        case "wmlsc":
            return "application/vnd.wap.wmlscriptc";
        case "wmv":
            return "video/x-ms-wmv";
        case "wmx":
            return "video/x-ms-wmx";
        case "wmz":
            return "application/x-ms-wmz";
        case "woff":
            return "application/font-woff";
        case "wp5":
            return "application/vnd.wordperfect5.1";
        case "wpd":
            return "application/vnd.wordperfect";
        case "wvx":
            return "video/x-ms-wvx";
        case "wz":
            return "application/x-wingz";
        case "x3d":
            return "model/x3d+xml";
        case "x3db":
            return "model/x3d+binary";
        case "x3dv":
            return "model/x3d+vrml";
        case "xbm":
            return "image/x-xbitmap";
        case "xcf":
            return "application/x-xcf";
        case "xcos":
            return "application/x-scilab-xcos";
        case "xht":
        case "xhtml":
            return "application/xhtml+xml";
        case "xlam":
            return "application/vnd.ms-excel.addin.macroEnabled.12";
        case "xlb":
        case "xls":
        case "xlt":
            return "application/vnd.ms-excel";
        case "xlsb":
            return "application/vnd.ms-excel.sheet.binary.macroEnabled.12";
        case "xlsm":
            return "application/vnd.ms-excel.sheet.macroEnabled.12";
        case "xlsx":
            return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        case "xltm":
            return "application/vnd.ms-excel.template.macroEnabled.12";
        case "xltx":
            return "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
        case "xml":
        case "xsd":
            return "application/xml";
        case "xpi":
            return "application/x-xpinstall";
        case "xpm":
            return "image/x-xpixmap";
        case "xsl":
        case "xslt":
            return "application/xslt+xml";
        case "xspf":
            return "application/xspf+xml";
        case "xtel":
            return "chemical/x-xtel";
        case "xul":
            return "application/vnd.mozilla.xul+xml";
        case "xwd":
            return "image/x-xwindowdump";
        case "xyz":
            return "chemical/x-xyz";
        case "xz":
            return "application/x-xz";
        case "zip":
            return "application/zip";
        default:
            return "";
    }
}
